# Generated by Django 2.0.8 on 2018-08-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleType', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=10)),
                ('amount', models.CharField(max_length=3)),
                ('timeIn', models.CharField(max_length=30)),
            ],
        ),
    ]
