# Generated by Django 2.0 on 2018-08-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0002_auto_20180811_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='timeOut',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
