# Generated by Django 2.0 on 2018-08-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0009_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatePost',
            fields=[
                ('vehicleNumber', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
